 // SPDX-License-Identifier: MIT                                                                                                                                                                                                                          
 pragma solidity ^0.8.20;                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                          
 /**                                                                                                                                                                                                                                                      
  * @title ProtocolParams                                                                                                                                                                                                                                 
  * @notice Manages protocol-wide parameters for the Seismic network                                                                                                                                                                                      
  * @dev Only the contract owner can set parameters, but anyone can read them                                                                                                                                                                             
  */                                                                                                                                                                                                                                                      
 contract ProtocolParams {                                                                                                                                                                                                                                
     /// @notice Maximum length for parameter values in bytes                                                                                                                                                                                             
     uint256 public constant MAX_PARAM_LENGTH = 100;                                                                                                                                                                                                      
                                                                                                                                                                                                                                                          
     /// @notice Address of the contract owner                                                                                                                                                                                                            
     address public owner;                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                          
     /// @notice Mapping from parameter ID to parameter value                                                                                                                                                                                             
     mapping(uint8 => bytes) private params;                                                                                                                                                                                                              
                                                                                                                                                                                                                                                          
     /// @notice Emitted when a protocol parameter is set or updated                                                                                                                                                                                      
     /// @param param_id The ID of the parameter                                                                                                                                                                                                          
     /// @param param The new value of the parameter                                                                                                                                                                                                      
     event ProtocolParamEvent(uint8 param_id, bytes param);                                                                                                                                                                                               
                                                                                                                                                                                                                                                          
     /// @notice Emitted when ownership is transferred                                                                                                                                                                                                    
     /// @param previousOwner The address of the previous owner                                                                                                                                                                                           
     /// @param newOwner The address of the new owner                                                                                                                                                                                                     
     event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);                                                                                                                                                                 
                                                                                                                                                                                                                                                          
     error OnlyOwner();                                                                                                                                                                                                                                   
     error ParamTooLarge(uint256 length, uint256 maxLength);                                                                                                                                                                                              
     error ZeroAddress();                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                          
     modifier onlyOwner() {                                                                                                                                                                                                                               
         if (msg.sender != owner) revert OnlyOwner();                                                                                                                                                                                                     
         _;                                                                                                                                                                                                                                               
     }                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          
     /**                                                                                                                                                                                                                                                  
      * @notice Constructs the ProtocolParams contract                                                                                                                                                                                                    
      * @dev Sets the deployer as the initial owner                                                                                                                                                                                                       
      */                                                                                                                                                                                                                                                  
     constructor() {                                                                                                                                                                                                                                      
         owner = msg.sender;                                                                                                                                                                                                                              
         emit OwnershipTransferred(address(0), msg.sender);                                                                                                                                                                                               
     }                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          
     /**                                                                                                                                                                                                                                                  
      * @notice Sets or updates a protocol parameter                                                                                                                                                                                                      
      * @dev Only callable by the owner. Emits ProtocolParamEvent on success.                                                                                                                                                                             
      * @param param_id The ID of the parameter to set (0-255)                                                                                                                                                                                            
      * @param param The value to set (max 100 bytes)                                                                                                                                                                                                     
      */                                                                                                                                                                                                                                                  
     function set_param(uint8 param_id, bytes calldata param) external onlyOwner {                                                                                                                                                                        
         if (param.length > MAX_PARAM_LENGTH) {                                                                                                                                                                                                           
             revert ParamTooLarge(param.length, MAX_PARAM_LENGTH);                                                                                                                                                                                        
         }                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                          
         params[param_id] = param;                                                                                                                                                                                                                        
         emit ProtocolParamEvent(param_id, param);                                                                                                                                                                                                        
     }                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          
     /**                                                                                                                                                                                                                                                  
      * @notice Retrieves the value of a protocol parameter                                                                                                                                                                                               
      * @param param_id The ID of the parameter to retrieve (0-255)                                                                                                                                                                                       
      * @return The value of the parameter (empty bytes if not set)                                                                                                                                                                                       
      */                                                                                                                                                                                                                                                  
     function get_param(uint8 param_id) external view returns (bytes memory) {                                                                                                                                                                            
         return params[param_id];                                                                                                                                                                                                                         
     }                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          
     /**                                                                                                                                                                                                                                                  
      * @notice Checks if a parameter has been set                                                                                                                                                                                                        
      * @param param_id The ID of the parameter to check                                                                                                                                                                                                  
      * @return True if the parameter has a non-empty value                                                                                                                                                                                               
      */                                                                                                                                                                                                                                                  
     function has_param(uint8 param_id) external view returns (bool) {                                                                                                                                                                                    
         return params[param_id].length > 0;                                                                                                                                                                                                              
     }                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          
     /**                                                                                                                                                                                                                                                  
      * @notice Transfers ownership of the contract to a new address                                                                                                                                                                                      
      * @dev Only callable by the current owner                                                                                                                                                                                                           
      * @param newOwner The address of the new owner                                                                                                                                                                                                      
      */                                                                                                                                                                                                                                                  
     function transferOwnership(address newOwner) external onlyOwner {                                                                                                                                                                                    
         if (newOwner == address(0)) revert ZeroAddress();                                                                                                                                                                                                
         address oldOwner = owner;                                                                                                                                                                                                                        
         owner = newOwner;                                                                                                                                                                                                                                
         emit OwnershipTransferred(oldOwner, newOwner);                                                                                                                                                                                                   
     }                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          
     /**                                                                                                                                                                                                                                                  
      * @notice Renounces ownership of the contract                                                                                                                                                                                                       
      * @dev Leaves the contract without an owner, disabling owner-only functions                                                                                                                                                                         
      * @dev Use with caution as this action is irreversible                                                                                                                                                                                              
      */                                                                                                                                                                                                                                                  
     function renounceOwnership() external onlyOwner {                                                                                                                                                                                                    
         address oldOwner = owner;                                                                                                                                                                                                                        
         owner = address(0);                                                                                                                                                                                                                              
         emit OwnershipTransferred(oldOwner, address(0));                                                                                                                                                                                                 
     }                                                                                                                                                                                                                                                    
 } 
